DROP TABLE IF EXISTS CAR;  
CREATE TABLE CAR (  
id INT AUTO_INCREMENT PRIMARY KEY,  
name VARCHAR(50) NOT NULL,  
manufacture_name VARCHAR(50) NOT NULL,  
model VARCHAR(50) NOT NULL, 
manufacturing_year VARCHAR(50) NOT NULL, 
color VARCHAR(50) NOT NULL, 
);  
DROP TABLE IF EXISTS USER;  
CREATE TABLE USER (  
id INT AUTO_INCREMENT PRIMARY KEY,  
email_id VARCHAR(50) NOT NULL,  
password VARCHAR(50) NOT NULL, 
);  